version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        container_name: 'chat-service-server'
        ports:
            - '${APP_PORT:-9901}:80'
            - '${LARAVEL_WEBSOCKETS_PORT:-6101}:6101'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql

    mysql:
        image: 'mysql:latest'
        container_name: 'chat-service-mysql'
        ports:
            - '${FORWARD_DB_PORT:-3666}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './docker/db:/var/lib/mysql'
        networks:
            - sail

    phpmyadmin:
        image: phpmyadmin
        container_name: 'chat-service-pma'
        environment:
            PMA_HOST: '${DB_HOST}'
            PMA_PORT: '${DB_PORT}'
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - '${PMA_PORT:-6565}:80'
        networks:
            - sail
        depends_on:
            - mysql
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
